- id: '1590061088891'
  alias: Garage Open Notify
  description: ''
  trigger:
  - entity_id: cover.garage
    for: 00:15:00
    from: closed
    platform: state
    to: open
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: device_tracker.pixel_3
      state: not_home
    - condition: state
      entity_id: device_tracker.pixel_3
      state: Work
    - condition: state
      entity_id: device_tracker.pixel_3
      state: Jon's
    - condition: state
      entity_id: device_tracker.pixel_3
      state: Zach's
    - condition: state
      entity_id: device_tracker.pixel_3
      state: Mom & Dad's
    - condition: state
      entity_id: device_tracker.pixel_3
      state: Derek & Ruby's
    - condition: state
      entity_id: device_tracker.pixel_3
      state: Colleen's
  action:
  - data:
      data:
        actions:
        - action: close_garage
          title: Close Garage Door
      message: The garage has been left open
    service: notify.mobile_app_pixel_3
  mode: single
- id: '1590063296958'
  alias: Garage Offline Notify
  description: ''
  trigger:
  - entity_id: binary_sensor.garage_control_online
    for: 00:05:00
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: The garage went offline.
      title: GARAGE OFFLINE ALERT!!!
    service: notify.mobile_app_pixel_3
- id: '1590063647022'
  alias: Startup Theme
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: darkred
    service: frontend.set_theme
- id: '1590064903061'
  alias: Garage Close When Tapped
  description: ''
  trigger:
  - event_data:
      action: close_garage
    event_type: mobile_app_notification_action
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: cover.garage
    service: cover.close_cover
  mode: single
- id: '1590065278680'
  alias: Camera Recordings ON
  description: ''
  trigger:
  - entity_id: device_tracker.pixel_3
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - data: {}
    entity_id: all
    service: amcrest.enable_motion_recording
- id: '1590065333625'
  alias: Camera Recordings OFF
  description: ''
  trigger:
  - entity_id: device_tracker.pixel_3
    event: enter
    platform: zone
    zone: zone.home
  condition: []
  action:
  - service: amcrest.disable_motion_recording
    data: {}
    entity_id: camera.den_2
  - service: amcrest.disable_motion_recording
    data: {}
    entity_id: camera.living
  - service: amcrest.disable_motion_recording
    data: {}
    entity_id: camera.garage
  mode: single
- id: '1590089147873'
  alias: Certificates Expiring
  description: ''
  trigger:
  - below: '15'
    entity_id: sensor.cert_expiry_redwngsrul_duckdns_org_8123
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Your certificates have less than 15 days before expiring. Please renew
        now!
      title: Certificates are Expiring!!!
    service: notify.gmail
  - data:
      message: Your certificates have less than 15 days before expiring. Please renew
        now!
      title: Certificates are Expiring!!!
    service: persistent_notification.create
  mode: single
- id: '1590089543452'
  alias: Ecobee Vacation
  description: ''
  trigger:
  - entity_id: device_tracker.pixel_3
    for: '24:00:00'
    platform: state
    to: not_home
  - entity_id: device_tracker.pixel_3
    platform: state
    to: Jon's
  - entity_id: device_tracker.pixel_3
    platform: state
    to: Zach's
  - entity_id: device_tracker.pixel_3
    platform: state
    to: Mom & Dad's
  - entity_id: device_tracker.pixel_3
    platform: state
    to: Derek & Ruby's
  - platform: state
    entity_id: input_boolean.vacation
    to: 'on'
  condition: []
  action:
  - data:
      message: Ecobee Vacation Mode Enabled
    service: notify.mobile_app_pixel_3
  - data:
      cool_temp: 80
      entity_id: climate.thermostat
      heat_temp: 61
      vacation_name: HASS
    entity_id: climate.thermostat
    service: ecobee.create_vacation
  - data: {}
    entity_id: input_boolean.vacation
    service: input_boolean.turn_on
  mode: single
- id: '1590089677038'
  alias: Ecobee Cancel Vacation
  description: ''
  trigger:
  - entity_id: device_tracker.pixel_3
    platform: state
    to: Home
  condition:
  - condition: state
    entity_id: input_boolean.vacation
    state: 'on'
  action:
  - data:
      message: Ecobee Vacation Mode Cancelled
    service: notify.mobile_app_pixel_3
  - data:
      entity_id: climate.thermostat
      vacation_name: HASS
    service: ecobee.delete_vacation
- id: '1590090127678'
  alias: 5 - Bedtime
  description: ''
  trigger:
  - at: '22:30:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - sun
  action:
  - data: {}
    entity_id: switch.fish_tank
    service: switch.turn_off
  - data: {}
    entity_id: switch.neons
    service: switch.turn_off
  - data: {}
    entity_id: switch.oil_warmer
    service: switch.turn_off
  - data: {}
    entity_id: switch.office_oil_warmer
    service: switch.turn_off
  - data: {}
    entity_id: light.nanoleaf
    service: light.turn_off
  - data: {}
    entity_id: switch.bottle_lamp
    service: switch.turn_off
  - service: switch.turn_off
    data: {}
    entity_id: switch.christmas_tree
  - service: switch.turn_off
    data: {}
    entity_id: switch.sink_light
  mode: single
- id: '1590091422139'
  alias: Vacation Lights
  description: fake like someone is home during vacation
  trigger:
  - event: sunset
    offset: -00:29:59
    platform: sun
  - platform: sun
    event: sunset
    offset: +01:00:00
  - platform: time
    at: '22:30:00'
  condition:
  - condition: state
    entity_id: input_boolean.vacation
    state: 'on'
  action:
  - choose:
    - conditions:
      - condition: sun
        after_offset: -00:30:00
        before_offset: +01:00:00
        before: sunset
        after: sunset
      sequence:
      - service: switch.turn_on
        data: {}
        entity_id: switch.den_lamp
      - service: switch.turn_on
        data: {}
        entity_id: switch.bottle_lamp
      - service: switch.turn_on
        data: {}
        entity_id: switch.sink_light
    - conditions:
      - condition: sun
        after: sunset
        after_offset: +01:00:00
      sequence:
      - service: switch.turn_off
        data: {}
        entity_id: switch.den_lamp
      - service: switch.turn_on
        data: {}
        entity_id: switch.neons
    - conditions:
      - condition: time
        after: '22:29'
        before: '22:31'
      sequence:
      - service: switch.turn_off
        data: {}
        entity_id: switch.neons
      - service: switch.turn_off
        data: {}
        entity_id: switch.bottle_lamp
      - service: switch.turn_off
        data: {}
        entity_id: switch.sink_light
    default: []
  mode: single
- id: '1590092145859'
  alias: Motion Alarm Notify
  description: ''
  trigger:
  - entity_id: binary_sensor.den_2_motion_detected
    from: 'False'
    platform: state
  - entity_id: binary_sensor.garage_motion_detected
    from: 'False'
    platform: state
  - entity_id: binary_sensor.living_motion_detected
    from: 'False'
    platform: state
  - entity_id: binary_sensor.back_door_sensor
    platform: state
    to: 'on'
  - entity_id: binary_sensor.den_multisensor
    platform: state
    to: 'on'
  - entity_id: binary_sensor.front_door_motion_sensor
    platform: state
  - entity_id: binary_sensor.front_door_sensor
    platform: state
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: zone
      entity_id: device_tracker.pixel_3
      zone: zone.colleen_s
    - condition: zone
      entity_id: device_tracker.pixel_3
      zone: zone.derek_ruby_s
    - condition: zone
      entity_id: device_tracker.pixel_3
      zone: zone.jon_s
    - condition: zone
      entity_id: device_tracker.pixel_3
      zone: zone.zach_s
    - condition: zone
      entity_id: device_tracker.pixel_3
      zone: zone.mom_dad_s
    - condition: zone
      entity_id: device_tracker.pixel_3
      zone: zone.work
    - condition: state
      entity_id: device_tracker.pixel_3
      state: not_home
  action:
  - data:
      filename: /config/www/back_yard.jpg
    entity_id: camera.back_yard
    service: camera.snapshot
  - data:
      filename: /config/www/den_motion.jpg
    entity_id: camera.den_2
    service: camera.snapshot
  - data:
      filename: /config/www/front_porch_motion.jpg
    entity_id: camera.front_porch
    service: camera.snapshot
  - data:
      filename: /config/www/garage_motion.jpg
    entity_id: camera.garage
    service: camera.snapshot
  - data:
      filename: /config/www/living_room_motion.jpg
    entity_id: camera.living
    service: camera.snapshot
  - data:
      data:
        images:
        - /config/www/front_porch_motion.jpg
        - /config/www/living_room_motion.jpg
        - /config/www/garage_motion.jpg
        - /config/www/den_motion.jpg
        - /config/www/back_yard.jpg
      message: Motion detected.
      title: Motion detected!
    service: notify.gmail
  - data:
      message: Motion Detected in the House!!!
    service: notify.mobile_app_pixel_3
- id: '1597746589815'
  alias: Back Porch ON
  description: ''
  trigger:
  - platform: time
    at: 06:30:00
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.back_porch
  mode: single
- id: '1597746659782'
  alias: Back Porch OFF
  description: ''
  trigger:
  - event: sunset
    offset: +00:30:00
    platform: sun
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.back_porch
  mode: single
- id: '1605802114888'
  alias: 1 - Wake-up
  description: ''
  trigger:
  - platform: time
    at: 06:30:00
  - platform: time
    at: 07:00:00
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: state
      entity_id: input_boolean.vacation
      state: 'off'
  action:
  - choose:
    - conditions:
      - condition: time
        after: '6:29:59'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        before: 06:59:00
      sequence:
      - service: switch.turn_on
        data: {}
        entity_id: switch.bottle_lamp
      - service: switch.turn_on
        data: {}
        entity_id: switch.dining_room
      - service: switch.turn_on
        data: {}
        entity_id: switch.sink_light
    default: []
  - choose:
    - conditions:
      - condition: time
        after: '6:59:59'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: switch.turn_on
        data: {}
        entity_id: switch.laundry
    default: []
  mode: single
- id: '1605802565595'
  alias: 2 - Leave for Work
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.pixel_3
    from: home
    for: 00:05:00
  - platform: time
    at: 07:45:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    after: 06:30:00
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.bottle_lamp
  - service: switch.turn_off
    data: {}
    entity_id: switch.dining_room
  - service: switch.turn_off
    data: {}
    entity_id: switch.laundry
  - service: switch.turn_off
    data: {}
    entity_id: switch.sink_light
  mode: single
- id: '1605803090452'
  alias: 3 - Home from Work
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.pixel_3
    to: home
    for: 00:02:00
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.fish_tank
  - choose:
    - conditions:
      - condition: sun
        before: sunset
        after: sunset
        before_offset: -01:00:00
      sequence:
      - service: light.turn_on
        data:
          brightness: 254
        entity_id: light.nanoleaf
    - conditions:
      - condition: sun
        before: sunset
        after: sunset
        after_offset: -01:00:00
        before_offset: -00:15:00
      sequence:
      - service: light.turn_on
        data:
          brightness: 191
        entity_id: light.nanoleaf
    - conditions:
      - condition: sun
        before: sunset
        after: sunset
        after_offset: -00:15:00
        before_offset: +00:30:00
      sequence:
      - service: light.turn_on
        data:
          brightness: 127
        entity_id: light.nanoleaf
    - conditions:
      - condition: sun
        after: sunset
        after_offset: +00:30:00
      sequence:
      - service: light.turn_on
        data:
          brightness: 64
        entity_id: light.nanoleaf
    default: []
  mode: single
- id: '1605803157200'
  alias: 4 - Sundown
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -01:00:00
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.fish_tank
  - service: switch.turn_on
    data: {}
    entity_id: switch.bottle_lamp
  - service: switch.turn_on
    data: {}
    entity_id: switch.christmas_tree
  mode: single
- id: '1605803777753'
  alias: Nanoleaf Wind Down
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:59:59
  - platform: sun
    event: sunset
    offset: -00:14:59
  - platform: sun
    event: sunset
    offset: +00:30:01
  condition:
  - condition: state
    entity_id: light.nanoleaf
    state: 'on'
  action:
  - choose:
    - conditions:
      - condition: sun
        before: sunset
        after: sunset
        after_offset: -01:00:00
        before_offset: -00:15:00
      sequence:
      - service: light.turn_on
        data:
          brightness: 191
        entity_id: light.nanoleaf
    - conditions:
      - condition: sun
        before: sunset
        after: sunset
        after_offset: -00:15:00
        before_offset: +00:30:00
      sequence:
      - service: light.turn_on
        data:
          brightness: 127
        entity_id: light.nanoleaf
    - conditions:
      - condition: sun
        after: sunset
        after_offset: +00:30:00
      sequence:
      - service: light.turn_on
        data:
          brightness: 64
        entity_id: light.nanoleaf
    default: []
  mode: single
- id: '1611503340161'
  alias: 6 - Bedtime Weekend
  description: ''
  trigger:
  - at: 00:30:00
    platform: time
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - data: {}
    entity_id: switch.fish_tank
    service: switch.turn_off
  - data: {}
    entity_id: switch.neons
    service: switch.turn_off
  - data: {}
    entity_id: switch.oil_warmer
    service: switch.turn_off
  - data: {}
    entity_id: switch.office_oil_warmer
    service: switch.turn_off
  - data: {}
    entity_id: light.nanoleaf
    service: light.turn_off
  - data: {}
    entity_id: switch.bottle_lamp
    service: switch.turn_off
  - service: switch.turn_off
    data: {}
    entity_id: switch.christmas_tree
  - service: switch.turn_off
    data: {}
    entity_id: switch.sink_light
  mode: single
- id: '1612802696409'
  alias: Roomba Bin Full Notify
  description: ''
  trigger:
  - entity_id: binary_sensor.roomba_bin_full
    platform: state
    to: 'on'
    for: 00:05:00
  condition: []
  action:
  - data:
      message: Roomba Bin is FULL
    service: notify.mobile_app_pixel_3
  - service: persistent_notification.create
    data:
      message: Roomba Bin is FULL
  mode: single
- id: '1612881794745'
  alias: Z-Wave Low Battery Notify
  description: ''
  trigger:
  - entity_id: binary_sensor.den_zw_low_battery_level
    platform: state
    to: 'on'
    for: 00:05:00
  - entity_id: binary_sensor.front_door_low_battery_level
    platform: state
    to: 'on'
    for: 00:05:00
  - entity_id: binary_sensor.living_rm_low_battery_level
    platform: state
    to: 'on'
    for: 00:05:00
  - entity_id: binary_sensor.patio_door_low_battery_level_2
    platform: state
    to: 'on'
    for: 00:05:00
  condition: []
  action:
  - data:
      message: Z-Wave Low Battery Alarm
    service: notify.mobile_app_pixel_3
  mode: single
- id: '1612882010902'
  alias: HASS Update Available
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    to: 'on'
    for: 00:05:00
  condition: []
  action:
  - service: persistent_notification.create
    data:
      message: A new HASS update is available!
  mode: single
- id: '1612916563097'
  alias: Alex loves Colleen
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.vacation_monitor
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_sm_g975u
    data:
      message: Alex loves you!
  mode: single
- id: '1613608343746'
  alias: Bedroom ON
  description: ''
  trigger:
  - platform: state
    entity_id: switch.bedroom
    to: 'on'
  - platform: state
    entity_id: light.bedroom_fan
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.bedroom
  - service: light.turn_on
    data: {}
    entity_id: light.bedroom_fan
  mode: single
- id: '1613608361591'
  alias: Bedroom OFF
  description: ''
  trigger:
  - platform: state
    entity_id: switch.bedroom
    to: 'off'
  - platform: state
    entity_id: light.bedroom_fan
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.bedroom
  - service: light.turn_off
    data: {}
    entity_id: light.bedroom_fan
  mode: single
