- id: '1575132376722'
  alias: turn on multiple switches
  description: ''
  trigger:
  - entity_id: switch.dining_room_light
    platform: state
    to: 'on'
  condition: []
  action:
  - device_id: ee081b661ae6456fa0d6e8221a24eb20
    domain: switch
    entity_id: switch.bedroom
    type: turn_on
- id: '1575132496063'
  alias: turn off multiple switches
  description: ''
  trigger:
  - entity_id: switch.dining_room_light
    platform: state
    to: 'off'
  condition: []
  action:
  - device_id: ee081b661ae6456fa0d6e8221a24eb20
    domain: switch
    entity_id: switch.bedroom
    type: turn_off
