- platform: command_line
  command: 'ping -c 1 192.168.1.99 | grep "1 received" | wc -l'
  name: 'Garage Control Online'
  device_class: connectivity
  payload_on: 1
  payload_off: 0
  
- platform: command_line
  command: !secret den_cam_rcrding
  name: 'Den Camera Recording'
  payload_on: 1
  payload_off: 0

- platform: command_line
  command: !secret garage_cam_rcrding
  name: 'Garage Camera Recording'
  payload_on: 1
  payload_off: 0

- platform: workday
  country: US
  province: OH

- platform: template
  sensors:
    vacation_monitor:
      friendly_name: 'Vacation Monitor'
      value_template: "{{ is_state('input_boolean.vacation', 'on') }}" 

# dummy sensor for floorplan card
- platform: mqtt
  state_topic: dummy/floorplan/sensor
  name: Floorplan
