homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Detroit
  customize: !include customize.yaml

amcrest: !include amcrest.yaml

automation: !include_dir_merge_list automation

binary_sensor: !include binary_sensors.yaml

camera: !include cameras.yaml

cloud:

config:

conversation:

cover: !include cover.yaml

device_tracker: !include device_tracker.yaml

discovery:

frontend: !include frontend.yaml

google_assistant: !include goog_asst.yaml

group: !include group.yaml

history: !include history.yaml

history_graph: !include history_graph.yaml

http:
  ssl_certificate: !secret sslcert 
  ssl_key: !secret sslkey
  base_url: !secret urlname

input_boolean: !include input_boolean.yaml

input_number: !include input_slider.yaml

input_select: !include input_select.yaml

logbook:

logger:
  default: error
  logs:
    homeassistant.components.camera: error

map:

media_player:
  - platform: cast

mqtt: !include mqtt.yaml

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

notify: !include notifiers.yaml

panel_iframe:
  configurator:
    title: 'Yaml Editor'
    icon: mdi:wrench
    url: !secret yaml_editor_url

recorder:
  purge_interval: 3
  purge_keep_days: 5

script: !include scripts.yaml

sensor: !include sensors.yaml

shell_command: !include shell_commands.yaml

switch: !include switch.yaml

sun:

tts:
  - platform: google

updater:

vacuum:
  - platform: roomba
    host: 192.168.1.117
    username: !secret roomba_user
    password: !secret roomba_pw

zone: !include zones.yaml

