homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Detroit
  customize: !include yaml/customize.yaml

amcrest: !include yaml/amcrest.yaml

automation: !include_dir_merge_list yaml/automation

binary_sensor: !include yaml/binary_sensors.yaml

camera: !include yaml/cameras.yaml

cloud:

config:

conversation:

cover: !include yaml/cover.yaml

discovery:

frontend: !include yaml/frontend.yaml

google_assistant: !include yaml/goog_asst.yaml

history: !include yaml/history.yaml

http:
  ssl_certificate: !secret sslcert 
  ssl_key: !secret sslkey
  base_url: !secret urlname

input_boolean: !include yaml/input_boolean.yaml

input_number: !include yaml/input_slider.yaml

input_select: !include yaml/input_select.yaml

logbook:

logger:
  default: error
  logs:
    homeassistant.components.camera: error

lovelace:
  mode: yaml
  
map:

media_player:

mqtt: !include yaml/mqtt.yaml

# nest:
#   client_id: !secret nest_id
#   client_secret: !secret nest_secret

notify: !include yaml/notifiers.yaml

owntracks:

panel_iframe:
  configurator:
    title: 'Yaml Editor'
    icon: mdi:wrench
    url: !secret yaml_editor_url

recorder:
  purge_interval: 3
  purge_keep_days: 5

script: !include yaml/scripts.yaml

sensor: !include yaml/sensors.yaml

shell_command: !include yaml/shell_commands.yaml

speedtestdotnet:
  monitored_conditions:
    - ping
    - upload
    - download
  scan_interval:
    days: 0
    hours: 8
    minutes: 0

stream:

switch: !include yaml/switch.yaml

sun:

system_health:

tplink:
  discovery: false
  switch:
    - host: 192.168.1.106
    - host: 192.168.1.109
    - host: 192.168.1.108
    - host: 192.168.1.113
    - host: 192.168.1.105
    - host: 192.168.1.114
    - host: 192.168.1.111
    - host: 192.168.1.65
    - host: 192.168.1.67
    - host: 192.168.1.90
    - host: 192.168.1.93

tts:
  - platform: google_translate
    service_name: google_say

updater:

vacuum:
  - platform: roomba
    host: 192.168.1.117
    username: !secret roomba_user
    password: !secret roomba_pw

weather: !include yaml/weather.yaml

zone: !include yaml/zones.yaml

zwave: 
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key
