homeassistant:
  auth_mfa_modules:
    - type: totp
  customize: !include yaml/customize.yaml

amcrest: !include yaml/amcrest.yaml

automation: !include automations.yaml

binary_sensor: !include yaml/binary_sensors.yaml

camera: !include yaml/cameras.yaml

cloud:

config:

conversation:

cover: !include yaml/cover.yaml

discovery:

frontend: !include yaml/frontend.yaml

google_assistant: !include yaml/goog_asst.yaml

history: !include yaml/history.yaml

http:
  ssl_certificate: !secret sslcert 
  ssl_key: !secret sslkey

input_boolean: !include yaml/input_boolean.yaml

light: !include yaml/lights.yaml

logbook:

logger:
  default: error
  logs:
    homeassistant.components.camera: error

lovelace:
  mode: storage
  
map:

media_player:

media_source:

mobile_app:

notify: !include yaml/notifiers.yaml

panel_iframe:
  configurator:
    title: 'Yaml Editor'
    icon: mdi:wrench
    url: !secret yaml_editor_url
  zwavejs:
    title: 'Z-wave to MQTT'
    icon: mdi:z-wave
    url: 'http://192.168.50.243:8091'

recorder:
  purge_keep_days: 5

scene: !include scenes.yaml

script: !include scripts.yaml

sensor: !include yaml/sensors.yaml

shell_command: !include yaml/shell_commands.yaml

speedtestdotnet:
  monitored_conditions:
    - ping
    - upload
    - download
  scan_interval:
    days: 0
    hours: 8
    minutes: 0

stream:

switch: !include yaml/switch.yaml

sun:

system_health:

tts:
  - platform: google_translate
    service_name: google_say

updater:

# weather: !include yaml/weather.yaml

# zwave: 
#   usb_path: /dev/ttyACM0
#   network_key: !secret zwave_key
