#DEN LAMP
- platform: mqtt
  name: Den Light
  state_topic: "/Den_Lamp/relay/state"
  command_topic: "/Den_Lamp/gpio/12"
  qos: 1
  payload_on: "1"
  payload_off: "0"
  retain: true

#FRONT LIGHT  
- platform: mqtt
  name: Bottle Lamp
  state_topic: "/Bottle_Lamp/relay/state"
  command_topic: "/Bottle_Lamp/gpio/12"
  qos: 1
  payload_on: "1"
  payload_off: "0"
  retain: true

#Family Room LIGHT
- platform: mqtt
  name: Living Room Light
  state_topic: "/Home_Lamp/relay/state"
  command_topic: "/Home_Lamp/gpio/12"
  qos: 1
  payload_on: "1"
  payload_off: "0"
  retain: true
  
#WOL
- platform: wake_on_lan
  mac_address: !secret desktop_mac_addr
  name: Desktop
  host: "DESKTOP-PBK1QHJ"
  turn_off:
    service: shell_command.turn_off_desktop
  
#FISH TANK WHITE
- platform: mqtt
  name: Fish Tank White Light
  state_topic: "home-assistant/fish-tank/white"
  command_topic: "home-assistant/fish-tank"
  qos: 1
  payload_on: "WHITE"
  payload_off: "OFF"
  retain: true
  
#FISH TANK BLUE
- platform: mqtt
  name: Fish Tank Blue Light
  state_topic: "home-assistant/fish-tank/blue"
  command_topic: "home-assistant/fish-tank"
  qos: 1
  payload_on: "BLUE"
  payload_off: "OFF"
  retain: true
 
#DEN Camera Motion
- platform: command_line
  switches:
   #Switch for Foscam Motion Detection Recording
   den_camera_recording:
     command_on: !secret den_cmd_on
     command_off: !secret den_cmd_off
     command_state: !secret den_cmd_state
     value_template: '{{ value == "8" }}'
     friendly_name: Den Cam Record Motion
     
#Garage Camera Motion
- platform: command_line
  switches:
   #Switch for Foscam Motion Detection Recording
   garage_camera_recording:
     command_on: !secret garage_cmd_on
     command_off: !secret garage_cmd_off
     command_state: !secret garage_cmd_state
     value_template: '{{ value == "8" }}'
     friendly_name: Garage Cam Record Motion
 
#Template Switch for Den Game Equipment
- platform: template
  switches:
    game_equipment:
      value_template: "{{ is_state('input_boolean.game_equipment', 'on') }}"
      turn_on:
        service: script.turn_on
        data:
          entity_id: script.play_playstation4
      turn_off:
        service: script.turn_on
        data:
          entity_id: script.play_turn_off
