resources:
  - url: /local/custom-lovelace/mini-graph-card-bundle.js
    type: module
  - url: /local/custom-lovelace/button-card.js
    type: module
  - url: /local/custom-lovelace/simple-thermostat.js
    type: module  
#   - url: /local/custom-lovelace/compact-custom-header.js #?disable_cch
#     type: module

# cch:
#   header: false
#   default_tab: 0
#   voice: overflow
#   notifications: show
#   options: show
#   swipe: true
#   swipe_animate: swipe

title: My Home

views:
  - !include lovelace/00_Overview.yaml
  - !include lovelace/10_Systems.yaml
  - !include lovelace/20_Cast.yaml
  - !include lovelace/30_Automations_Scripts.yaml
  - !include lovelace/40_Cameras.yaml
