resources:
  - url: /local/custom-lovelace/mini-graph-card-bundle.js
    type: module
  - url: /local/custom-lovelace/button-card.js
    type: module
  - url: /local/custom-lovelace/simple-thermostat.js
    type: module
  - url: /local/custom-lovelace/mini-media-player-bundle.js
    type: module
  - url: /local/floorplan/floorplan-card.js
    type: module
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js #?v=1.3.0 #?disable_cch
    type: module

cch:
  voice: overflow
  notifications: show
  options: clock
  clock_date: true
  swipe: true
  swipe_animate: flip

title: My Home

views:
  - !include yaml/lovelace/00_Overview.yaml
#   - !include yaml/lovelace/05_Floorplan.yaml
  - !include yaml/lovelace/15_Weather.yaml
  - !include yaml/lovelace/10_Systems.yaml
  - !include yaml/lovelace/20_Cast.yaml
  - !include yaml/lovelace/30_Automations_Scripts.yaml
