- alias: Android Notify Garage Open
  trigger:
    platform: state
    entity_id: cover.garage
    from: 'closed'
    to: 'open'
    for: '00:30:00'
  action:
    service: notify.mobile_app_pixel_3
    data:
      message: "The garage has been left open"
      data:
        # image: https://www.home-assistant.io/images/merchandise/shirt-frontpage.png
        actions:
          - action: "close_garage" # The key you are sending for the event
            title: "Close Garage Door" # The button title

- alias: Android Close Garage When Tapped
  trigger:
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: close_garage
  action:
    service: cover.close_cover
    entity_id: cover.garage

#Garage Offline Notifier
- alias: "Garage Offline Notify"
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_control_online
      to: 'off'
      for:
        minutes: 5
  action:
      service: notify.mobile_app_pixel_3
      data:
        title: 'GARAGE OFFLINE ALERT!!!'
        message: 'The garage went offline.'

- alias: Android Notify Motion Detected
  trigger:
    - platform: state
      entity_id: sensor.front_porch_motion_detected
      from: 'False'
    - platform: state
      entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
      from: '0'
    - platform: state
      entity_id: sensor.hank_electronics_ltd_hkzw_dws01_door_window_sensor_access_control
      from: '23'
    - platform: state
      entity_id: sensor.hank_electronics_ltd_hkzw_dws01_door_window_sensor_access_control_2
      from: '23'
    - platform: state
      entity_id: sensor.hank_electronics_ltd_hkzw_dws01_door_window_sensor_burglar
      from: '0'
    - platform: state
      entity_id: sensor.hank_electronics_ltd_hkzw_dws01_door_window_sensor_burglar_2
      from: '0'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: device_tracker.pixel_3
        state: not_home
      - condition: state
        entity_id: device_tracker.pixel_3
        state: Work
      - condition: state
        entity_id: device_tracker.pixel_3
        state: "Jon's"
      - condition: state
        entity_id: device_tracker.pixel_3
        state: "Zach's"
      - condition: state
        entity_id: device_tracker.pixel_3
        state: "Mom & Dad's"
      - condition: state
        entity_id: device_tracker.pixel_3
        state: "Derek & Ruby's"
  action:
    service: notify.mobile_app_pixel_3
    data:
      message: "Motion Detected in the House!!!"
    #   data:
    #     actions:
    #       - action: 
    #         title: ""
