#Turn Camera Recordings ON
- alias: "Camera Recordings ON"
  trigger:
    - platform: state
      entity_id: device_tracker.pixel_3
      from: 'home'
  action:
    - service: amcrest.enable_motion_recording
      entity_id: camera.living
    - service: amcrest.enable_motion_recording
      entity_id: camera.front_porch
    - service: amcrest.enable_motion_recording
      entity_id: camera.den_2
    - service: amcrest.enable_motion_recording
      entity_id: camera.back_yard
    - service: amcrest.enable_motion_recording
      entity_id: camera.garage
    # - service: switch.turn_on
    #   entity_id: switch.garage_camera_recording
        
#Turn Camera Recordings OFF
- alias: "Camera Recordings OFF"
  trigger:
    - platform: state
      entity_id: device_tracker.pixel_3
      to: 'home'
      for:
        minutes: 3
  action:
    - service: amcrest.disable_motion_recording
      entity_id: camera.living
    - service: amcrest.disable_motion_recording
      entity_id: camera.front_porch
    - service: amcrest.disable_motion_recording
      entity_id: camera.den_2
    - service: amcrest.disable_motion_recording
      entity_id: camera.back_yard
    - service: amcrest.disable_motion_recording
      entity_id: camera.garage
    # - service: switch.turn_off
    #   entity_id: switch.garage_camera_recording