- alias: Ecobee Automatic Vacation
  trigger:
    - platform: state
      entity_id: device_tracker.pixel_3
      to: not_home
      for: "24:00:00"
    - platform: state
      entity_id: device_tracker.pixel_3
      to: "Jon's"
    - platform: state
      entity_id: device_tracker.pixel_3
      to: "Zach's"
    - platform: state
      entity_id: device_tracker.pixel_3
      to: "Mom & Dad's"
    - platform: state
      entity_id: device_tracker.pixel_3
      to: "Derek & Ruby's"
  condition:
    - condition: state
      entity_id: binary_sensor.vacation_monitor
      state: "off"
  action:
    - service: notify.mobile_app_pixel_3
      data:
        message: "Ecobee Automatic Vacation Mode Enabled"
    - service: ecobee.create_vacation
      data:
        entity_id: climate.thermostat
        vacation_name: HASS
        cool_temp: 80
        heat_temp: 61
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.vacation

- alias: Ecobee Cancel Vacation
  trigger:
    - platform: state
      entity_id: input_boolean.vacation
      to: "off"
  action:
    - service: notify.mobile_app_pixel_3
      data:
        message: "Ecobee Vacation Mode Cancelled"
    - service: ecobee.delete_vacation
      data:
        entity_id: climate.thermostat
        vacation_name: HASS
