#turn on fish tank lights
- alias: 'Fish Tank Lights ON'
  initial_state: true
  trigger:
    - platform: state
      entity_id: device_tracker.pixel_3
      to: 'home'
      for:
        minutes: 5
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
  condition: 
    condition: and
    conditions:
      - condition: state
        entity_id: switch.fish_tank
        state: 'off'
      - condition: time
        before: '22:30:00'
  action:
    - service: switch.turn_on
      entity_id: switch.fish_tank

#turn off tank lights at bedtime
- alias: 'No Fish Lights at Bedtime'
  initial_state: true
  trigger:
    - platform: time
      at: '22:30:00'    
    - platform: sun
      event: sunrise
      offset: '+00:30:00'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: switch.fish_tank
        state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.fish_tank