- alias: 'Leaf Light ON'
  initial_state: true
  trigger:
    - platform: state
      entity_id: device_tracker.pixel_3
      to: "home"
      for: "00:03:00"
    # - platform: time
    #   at: '19:00:00'
  condition:
    condition: state
    entity_id: light.nanoleaf
    state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.nanoleaf
      
- alias: 'Leaf 75'
  initial_state: true
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  condition:
    condition: state
    entity_id: light.nanoleaf
    state: 'on'
  action:
    service: light.turn_on
    data:
      brightness: 175
      entity_id:
        - light.nanoleaf

- alias: 'Leaf 50'
  initial_state: true
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  condition:
    condition: state
    entity_id: light.nanoleaf
    state: 'on'
  action:
    service: light.turn_on
    data:
      brightness: 124
      entity_id:
        - light.nanoleaf

- alias: 'Leaf 33'
  initial_state: true
  trigger:
    platform: sun
    event: sunset
    offset: "+00:30:00"
  condition:
    condition: state
    entity_id: light.nanoleaf
    state: 'on'
  action:
    service: light.turn_on
    data:
      brightness: 81
      entity_id:
        - light.nanoleaf