#Front porch Motion Alarm Notifier
- alias: "Front Porch Motion Alarm Notify"
  trigger:
    - platform: state
      entity_id: sensor.front_porch_motion_detected
      from: 'False'
#      for:
#        minutes: 5
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: device_tracker.pixelxl_pixelxl_2
        state: not_home
#        for:
#          minutes: 2
      - condition: state
        entity_id: device_tracker.pixelxl_pixelxl_2
        state: "Zach's"
#        for:
#          minutes: 2
      - condition: state
        entity_id: device_tracker.pixelxl_pixelxl_2
        state: Work
#        for:
#          minutes: 2
      - condition: state
        entity_id: device_tracker.pixelxl_pixelxl_2
        state: "Mom & Dad's"
#        for:
#          minutes: 2
      - condition: state
        entity_id: device_tracker.pixelxl_pixelxl_2
        state: "Derek & Ruby's"
#        for:
#          minutes: 2
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.front_porch
        filename: '/config/www/front_porch_motion.jpg'
    - service: camera.snapshot
      data:
        entity_id: camera.living
        filename: '/config/www/living_room_motion.jpg'
    - service: camera.snapshot
      data:
        entity_id: camera.den_video
        filename: '/config/www/den_motion.jpg'
    - service: camera.snapshot
      data:
        entity_id: camera.garage_video
        filename: '/config/www/garage_motion.jpg'
    - service: notify.gmail
      data:
        title: 'Front porch motion detected!'
        message: 'Motion detected at the front door.'
        data:
          images: 
            - /config/www/front_porch_motion.jpg
            - /config/www/living_room_motion.jpg
            - /config/www/garage_motion.jpg
            - /config/www/den_motion.jpg

#Den Motion Alarm Notifier
- alias: "Motion Alarm Notify"
  trigger:
    - platform: state
      entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
      from: '0'
    - platform: state
      entity_id: sensor.hank_electronics_ltd_hkzw_dws01_door_window_sensor_access_control
      from: '23'
    - platform: state
      entity_id: sensor.hank_electronics_ltd_hkzw_dws01_door_window_sensor_access_control_2
      from: '23'
    - platform: state
      entity_id: sensor.hank_electronics_ltd_hkzw_dws01_door_window_sensor_burglar
      from: '0'
    - platform: state
      entity_id: sensor.hank_electronics_ltd_hkzw_dws01_door_window_sensor_burglar_2
      from: '0'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: device_tracker.pixelxl_pixelxl_2
        state: not_home
#        for:
#          minutes: 2
      - condition: state
        entity_id: device_tracker.pixelxl_pixelxl_2
        state: "Zach's"
#        for:
#          minutes: 2
      - condition: state
        entity_id: device_tracker.pixelxl_pixelxl_2
        state: Work
#        for:
#          minutes: 2
      - condition: state
        entity_id: device_tracker.pixelxl_pixelxl_2
        state: "Mom & Dad's"
#        for:
#          minutes: 2
      - condition: state
        entity_id: device_tracker.pixelxl_pixelxl_2
        state: "Derek & Ruby's"
#        for:
#          minutes: 2
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.front_porch
        filename: '/config/www/front_porch_motion.jpg'
    - service: camera.snapshot
      data:
        entity_id: camera.living
        filename: '/config/www/living_room_motion.jpg'
    - service: camera.snapshot
      data:
        entity_id: camera.den_video
        filename: '/config/www/den_motion.jpg'
    - service: camera.snapshot
      data:
        entity_id: camera.garage_video
        filename: '/config/www/garage_motion.jpg'
    - service: notify.gmail
      data:
        title: 'Motion detected!'
        message: 'Motion detected in the house.'
        data:
          images: 
            - /config/www/front_porch_motion.jpg
            - /config/www/living_room_motion.jpg
            - /config/www/garage_motion.jpg
            - /config/www/den_motion.jpg

