- platform: command_line
  command: 'ping -c 1 192.168.1.99 | grep "1 packets received" | wc -l'
  name: 'Garage Control Online'
  device_class: connectivity
  payload_on: 1
  payload_off: 0

- platform: rest
  name: "Den Camera Recording"
  resource: !secret den_address
  device_class: power
  scan_interval: 5
  value_template: >-
    {%- if "<record>1</record>" in value -%}
      {{ true }}
    {%- else -%}
      {{ false }}
    {%- endif -%}

- platform: rest
  name: "Den Motion Recording"
  resource: !secret den_state
  device_class: power
  scan_interval: 5
  value_template: >-
    {%- if "<linkage>8</linkage>" in value -%}
      {{ true }}
    {%- else -%}
      {{ false }}
    {%- endif -%}

- platform: rest
  name: "Den Motion"
  resource: !secret den_address
  device_class: motion
  scan_interval: 5
  value_template: >-
    {%- if "<motionDetectAlarm>2</motionDetectAlarm>" in value -%}
      {{ true }}
    {%- else -%}
      {{ false }}
    {%- endif -%}

- platform: rest
  name: "Den Sound"
  resource: !secret den_address
  device_class: sound
  scan_interval: 5
  value_template: >-
    {%- if "<soundAlarm>2</soundAlarm>" in value -%}
      {{ true }}
    {%- else -%}
      {{ false }}
    {%- endif -%}
    
###################################################################################

- platform: rest
  name: "Garage Camera Recording"
  resource: !secret garage_address
  device_class: power
  scan_interval: 5
  value_template: >-
    {%- if "<record>1</record>" in value -%}
      {{ true }}
    {%- else -%}
      {{ false }}
    {%- endif -%}

- platform: rest
  name: "Garage Motion Recording"
  resource: !secret garage_state
  device_class: power
  scan_interval: 5
  value_template: >-
    {%- if "<linkage>8</linkage>" in value -%}
      {{ true }}
    {%- else -%}
      {{ false }}
    {%- endif -%}

- platform: rest
  name: "Garage Motion"
  resource: !secret garage_address
  device_class: motion
  scan_interval: 5
  value_template: >-
    {%- if "<motionDetectAlarm>2</motionDetectAlarm>" in value -%}
      {{ true }}
    {%- else -%}
      {{ false }}
    {%- endif -%}

- platform: rest
  name: "Garage Sound"
  resource: !secret garage_address
  device_class: sound
  scan_interval: 5
  value_template: >-
    {%- if "<soundAlarm>2</soundAlarm>" in value -%}
      {{ true }}
    {%- else -%}
      {{ false }}
    {%- endif -%}

#- platform: command_line
#  command: !secret den_cam_rcrding
#  name: 'Den Camera Recording'
#  payload_on: 1
#  payload_off: 0

#- platform: command_line
#  command: !secret garage_cam_rcrding
#  name: 'Garage Camera Recording'
#  payload_on: 1
#  payload_off: 0

- platform: workday
  country: US
  province: OH

- platform: template
  sensors:
    vacation_monitor:
      friendly_name: 'Vacation Monitor'
      value_template: "{{ is_state('input_boolean.vacation', 'on') }}" 

    den_multisensor:
      friendly_name: 'Den Motion'
      value_template: "{{ is_state('sensor.aeon_labs_zw100_multisensor_6_burglar', '8') }}"
      device_class: motion

    front_door_sensor:
      friendly_name: 'Front Door Sensor'
      value_template: "{{ is_state('sensor.hank_electronics_ltd_hkzw_dws01_door_window_sensor_access_control_2', '22') }}"
      device_class: door

    back_door_sensor:
      friendly_name: 'Back Door Sensor'
      value_template: "{{ is_state('sensor.hank_electronics_ltd_hkzw_dws01_door_window_sensor_access_control', '22') }}"
      device_class: door

    front_door_motion_sensor:
      friendly_name: 'Front Door Motion Sensor'
      value_template: "{{ is_state('sensor.vision_security_zp3111_multisensor_4in1_alarm_level_2', '255') }}"
      device_class: motion

    # den_sound_out:
    #   friendly_name: 'Den Sound'
    #   value_template: "{{ is_state('sensor.den_sound', '2') }}"
    #   device_class: sound

    # garage_sound_out:
    #   friendly_name: 'Garage Sound'
    #   value_template: "{{ is_state('sensor.garage_sound', '2') }}"
    #   device_class: sound

    # den_motion_out:
    #   friendly_name: 'Den Motion'
    #   value_template: "{{ is_state('sensor.den_motion', '2') }}"
    #   device_class: motion

    # garage_motion_out:
    #   friendly_name: 'Garage Motion'
    #   value_template: "{{ is_state('sensor.garage_motion', '2') }}"
    #   device_class: motion

# dummy sensor for floorplan card
- platform: mqtt
  state_topic: dummy/floorplan/sensor
  name: Floorplan

- platform: zwave
