- platform: command_line
  command: 'ping -c 1 192.168.50.86 | grep "1 packets received" | wc -l'
  name: 'Garage Control Online'
  device_class: connectivity
  payload_on: 1
  payload_off: 0

# - name: Front Yard Person
#   platform: mqtt
#   state_topic: "frigate/front_yard/person"
#   device_class: motion
#   availability_topic: "frigate/available"

# - name: Front Yard Car
#   platform: mqtt
#   state_topic: "frigate/front_yard/car"
#   device_class: motion
#   availability_topic: "frigate/available"

- platform: ping
  host: 192.168.50.88
  name: "Desktop"
  count: 1
  scan_interval: 60

- platform: workday
  country: US
  province: OH

- platform: template
  sensors:
    vacation_monitor:
      friendly_name: 'Vacation Monitor'
      value_template: "{{ is_state('input_boolean.vacation', 'on') }}" 

    back_yard_cam_recording:
      friendly_name: 'Back Yard Cam Recording'
      value_template: "{{ states.camera.back_yard.attributes.motion_recording == 'on' }}"
      device_class: moving

    den_cam_recording:
      friendly_name: 'Den Cam Recording'
      value_template: "{{ states.camera.den_2.attributes.motion_recording == 'on' }}"
      device_class: moving

    front_porch_cam_recording:
      friendly_name: 'Front Porch Cam Recording'
      value_template: "{{ states.camera.front_porch.attributes.motion_recording == 'on' }}"
      device_class: moving
      
    garage_cam_recording:
      friendly_name: 'Garage Cam Recording'
      value_template: "{{ states.camera.garage.attributes.motion_recording == 'on' }}"
      device_class: moving

    living_rm_cam_recording:
      friendly_name: 'Living Rm Cam Recording'
      value_template: "{{ states.camera.living.attributes.motion_recording == 'on' }}"
      device_class: moving
