- platform: amcrest

# - name: front_yard Last Person
#   platform: mqtt
#   topic: frigate/front_yard/person/snapshot
# - name: front_yard Last Car
#   platform: mqtt
#   topic: frigate/front_yard/car/snapshot

# - platform: generic
#   name: Garage Video
#   still_image_url: !secret garage_stream_jpg
#   stream_source: !secret garage_stream
#   username: !secret cam_un
#   password: !secret cam_pw