# - platform: generic
#   name: Den Video
#   still_image_url: !secret den_stream_jpg
#   stream_source: !secret den_stream
#   username: !secret cam_un
#   password: !secret cam_pw

- platform: generic
  name: Garage Video
  still_image_url: !secret garage_stream_jpg
  stream_source: !secret garage_stream
  username: !secret cam_un
  password: !secret cam_pw

- platform: amcrest
