- platform: moon

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: last_boot
    - type: ipv4_address
      arg: eth0
    - type: processor_use

- platform: qnap
  host: redwngsrul.myqnapcloud.com
  port: 50443
  ssl: true
  username: !secret qnap_user
  password: !secret qnap_pw
  monitored_conditions:
    - status
    - cpu_usage
    - memory_percent_used
    - volume_percentage_used

- platform: mqtt
  state_topic: "/Garage/Temp/Temperature"
  name: "Garage Temp"
  unit_of_measurement: "°F"
  qos: 1

- platform: template
  sensors:
    garage_status:
      friendly_name: 'Garage Status'
      value_template: '{{ states.cover.garage.state }}'
    garage_status_abbr:
      friendly_name: 'Garage'
      value_template: '{% if is_state("sensor.garage_status", "closed") %} CL {% else %} OP {% endif %}'
    nas_uptime:
      friendly_name: 'NAS Run Time'
      value_template: '{{ states.sensor.nasf34bde_status.attributes.Uptime }}'
    weather_temp:
      friendly_name: 'Weather Temp'
      value_template: '{{ state_attr("weather.thermostat","temperature") }}'
    weather_humid:
      friendly_name: 'Weather Humidity'
      value_template: '{{ state_attr("weather.thermostat","humidity") }}'
    moonphases:
      friendly_name: 'Moon Phases'
      value_template: '{{ states.sensor.moon.state }}'
      entity_picture_template: >
        {% if is_state('sensor.moon', 'new_moon') %}
          /local/moonphases/new.jpg
        {% elif is_state('sensor.moon', 'waxing_crescent') %}
          /local/moonphases/waxing_crescent.jpg
        {% elif is_state('sensor.moon', 'first_quarter') %}
          /local/moonphases/first_quarter.jpg
        {% elif is_state('sensor.moon', 'waxing_gibbous') %}
          /local/moonphases/waxing_gibbous.jpg
        {% elif is_state('sensor.moon', 'full_moon') %}
          /local/moonphases/full.jpg
        {% elif is_state('sensor.moon', 'waning_gibbous') %}
          /local/moonphases/waning_gibbous.jpg
        {% elif is_state('sensor.moon', 'last_quarter') %}
          /local/moonphases/last.jpg
        {% elif is_state('sensor.moon', 'waning_crescent') %}
          /local/moonphases/waning_crescent.jpg
        {% endif %}
    # front_yard_fps: 
    #   value_template: '{{ states.sensor.frigate_debug.attributes["front_yard"]["camera_fps"] }}'
    #   unit_of_measurement: 'FPS'
    # front_yard_skipped_fps: 
    #   value_template: '{{ states.sensor.frigate_debug.attributes["front_yard"]["skipped_fps"] }}'
    #   unit_of_measurement: 'FPS'
    # front_yard_detection_fps: 
    #   value_template: '{{ states.sensor.frigate_debug.attributes["front_yard"]["detection_fps"] }}'
    #   unit_of_measurement: 'FPS'
    # frigate_detection_fps: 
    #   value_template: '{{ states.sensor.frigate_debug.attributes["detection_fps"] }}'
    #   unit_of_measurement: 'FPS'

# - platform: rest
#   name: Frigate Debug
#   resource: http://192.168.50.243:5000/debug/stats
#   scan_interval: 5
#   json_attributes:
#     - front_yard
#     - detection_fps
#     - detectors
#   value_template: 'OK'

- platform: version
