#FRONT LIGHT  
- platform: mqtt
  name: Bottle Lamp
  state_topic: "/Bottle_Lamp/relay/state"
  command_topic: "/Bottle_Lamp/gpio/12"
  qos: 1
  payload_on: "1"
  payload_off: "0"
  retain: true
  
#WOL
# - platform: wake_on_lan
#   mac: !secret desktop_mac_addr
#   name: Desktop
#   host: 192.168.50.88
#   turn_off:
#     service: shell_command.turn_off_desktop
 
#Template Switch for Den Game Equipment
- platform: template
  switches:
    game_equipment:
      value_template: "{{ is_state('input_boolean.game_equipment', 'on') }}"
      turn_on:
        service: script.turn_on
        data:
          entity_id: script.play_playstation4
      turn_off:
        service: script.turn_on
        data:
          entity_id: script.play_turn_off
